id: costpilot.demo.v1
version: "1.0.0"
description: >
  Canonical reproducible demonstration repository for CostPilot.
  All marketing screenshots, videos, product documentation examples,
  and PR walk-throughs MUST originate from this repo.
  This environment must remain deterministic, hash-stable, and drift-safe.

scenario_version: "v1"

# ===========================================================
# 1. REPO OBJECTIVES
# ===========================================================
objectives:
  - "Provide a deterministic, reproducible end-to-end demonstration of CostPilot."
  - "Showcase the Trust Triangle: Detect → Predict → Explain."
  - "Demonstrate snippet-based autofix and patch preview (EC2 + S3 only)."
  - "Demonstrate mapping, trend, and snapshot reproducibility."
  - "Provide assets for launch video and marketing pages."
  - "Remain lightweight and safe for public consumption."

# ===========================================================
# 2. BRANCHES & PR METADATA
# ===========================================================
branches:
  baseline: "main"
  pr_branch: "feature/cost-regression-demo"
sample_pr_number: 42

# ===========================================================
# 3. DIRECTORY STRUCTURE
# ===========================================================
structure:
  - README.md
  - infrastructure/
      terraform/
        baseline/
          - main.tf
          - variables.tf
          - outputs.tf
        pr-change/
          - main.tf
          - variables.tf
          - outputs.tf
        noop-change/
          - main.tf
          - variables.tf
  - snapshots/
      - plan_before.json
      - plan_after.json
      - plan_diff.json
      - detect_v1.json
      - predict_v1.json
      - explain_v1.json
      - snippet_v1.tf
      - patch_v1.diff
  - .costpilot/
      demo/
        - detect_v1.json
        - predict_v1.json
        - explain_v1.json
        - snippet_v1.tf
        - patch_v1.diff
        - mapping_v1.mmd
        - trend_history.json
        - trend_v1.svg
  - costpilot_artifacts/
      - output_detect.json
      - output_predict.json
      - output_explain.json
      - output_snippet.tf
      - output_patch.diff
      - output_mapping.mmd
      - output_trend.json
  - tools/
      reset_demo.sh
  - .github/
      workflows/
        costpilot-ci.yml
  - costpilot.yml

# ===========================================================
# 4. TERRAFORM REQUIREMENTS
# ===========================================================
terraform_requirements:
  version: ">=1.6"
  plan_schema_version: 2

# ===========================================================
# 5. INFRASTRUCTURE SCENARIOS
# ===========================================================
scenarios:

  baseline_stack:
    description: "Intentionally cost-efficient baseline used for comparison."
    includes:
      - ec2_t3_micro_autoscaling_group
      - alb + target_group + listener
      - s3_bucket_with_lifecycle_enabled
      - cloudwatch_logs_with_30_day_retention
    guarantees:
      - "All baseline resources must represent stable, low-cost defaults."

  pr_regression_stack:
    description: "PR introduces regressions for detect/predict/explain demo."
    explicit_regressions:
      obvious:
        - ec2_instance_type_change: "t3.micro → t3.xlarge"
        - s3_lifecycle_disabled: true
      subtle:
        - cloudwatch_log_retention: "30 → infinite"
        - ebs_volume_size: "20GB → 200GB"
    cross_service_dependencies:
      - alb → target_group → autoscaling_group → ec2_instances
      - cloudwatch_logs → log_groups
    rationale: >
      Produces realistic cost propagation paths for mapping engine output.

  noop_change:
    description: "Used to demonstrate low false-positives. No findings expected."
    expected_output: "no_findings"

# ===========================================================
# 6. TRUST TRIANGLE VALIDATION
# ===========================================================
trust_triangle_validation:
  detect_step_must_show:
    - resource_classification
    - rule_ids
    - severity_scoring
  predict_step_must_show:
    - heuristic_references
    - ranges: [low, high]
    - cold_start_assumptions
  explain_step_must_show:
    - root_cause
    - regression_type
    - severity_score
    - heuristic_provenance
    - delta_justification

# ===========================================================
# 7. DETERMINISTIC CONSTRAINTS
# ===========================================================
deterministic_constraints:
  stable_hash_per_output_type: true
  float_precision_fixed: 2
  whitespace_normalization: true
  ordering_rules_enforced: true
  mapping_layout_seed_fixed: true
  trend_theme_fixed: true

# ===========================================================
# 8. DEMO OUTPUT REQUIREMENTS
# ===========================================================
demo_outputs:
  required:
    - detect_v1.json
    - predict_v1.json
    - explain_v1.json
    - snippet_v1.tf
    - patch_v1.diff
    - mapping_v1.mmd
    - trend_history.json
    - trend_v1.svg
  patch_preview_must_include:
    - diff
    - applies_cleanly
    - simulation_output.json:
        - before_hash
        - after_hash
        - patch_id
        - rollback_patch

# ===========================================================
# 9. PATCH PREVIEW SCOPE LIMIT
# ===========================================================
patch_preview_scope:
  supported_resources:
    - ec2_instance_type
    - s3_lifecycle_rule
  reason_for_scope_limit: >
    Networking and NAT gateway rewrites require broader context not available
    to deterministic snippet-mode demonstration.

# ===========================================================
# 10. TREND ENGINE DEMO
# ===========================================================
trend_demo:
  variations_required:
    - flat_trend
    - upward_trend
    - slo_breach_trend
  constraints:
    - fixed_seed_layout
    - deterministic_svg_dimensions: 800x300

# ===========================================================
# 11. RESET SCRIPT REQUIREMENTS
# ===========================================================
reset_demo_script:
  path: tools/reset_demo.sh
  must_do:
    - restore_baseline_infrastructure
    - regenerate_snapshots
    - regenerate_mapping
    - regenerate_trend_history
    - validate_deterministic_hashes
    - fail_if_drift_detected

# ===========================================================
# 12. CI GUARDRAILS
# ===========================================================
ci_guardrails:
  prevent_updates_to:
    - snapshots/*
    - costpilot_artifacts/*
    - video_assets/*
  allowlist_changes:
    - infrastructure/terraform/pr-change/*
    - README.md
    - costpilot.yml
  checks:
    - verify_deterministic_output:
        compare_with: "./snapshots/costpilot_snapshot_v1.json"
        fail_on_drift: true
    - test_noop_produces_no_findings: true

# ===========================================================
# 13. PERFORMANCE EXPECTATIONS
# ===========================================================
performance_expectations:
  detect_under_ms: 200
  predict_under_ms: 300
  explain_under_ms: 300

# ===========================================================
# 14. README REQUIREMENTS
# ===========================================================
readme_requirements:
  must_include:
    - hero_copy: "CostPilot — Predict, Detect & Explain Cloud Cost Regressions Before They Merge."
    - statement_of_purpose: >
        "This repository is the canonical demonstration environment for CostPilot.
         All screenshots, documentation examples and launch-day assets originate here."
    - quickstart_steps
    - sample_PR_walkthrough
    - mapping_example
    - trend_example
    - trust_triangle_section

# ===========================================================
# 15. ARTIFACT MANAGEMENT
# ===========================================================
artifacts:
  directory: "costpilot_artifacts/"
  contains_dynamic_outputs: true
  must_be_deterministic: true

# ===========================================================
# 16. LICENSING & ATTRIBUTION
# ===========================================================
license: "MIT"
sidebar_note: "Safe for public tutorials, demos, and launch content."

# ===========================================================
# 17. EXPECTED PR SCENARIO CHECKSUM
# ===========================================================
expected_pr_scenario:
  version: "1.0.0"
  canonical_spec_hash: "<fill_after_generation>"
  invariants:
    - snapshots_must_match_hash
    - explain_output_must_match_hash

# ===========================================================
# 18. EXCLUSIONS
# ===========================================================
explicit_exclusions:
  - no_enterprise_demo
  - no_enterprise_policies
  - no_exemptions_demo
  - no_slo_burn_reports
  - no_team_attribution
  rationale: "The demo repo must remain lightweight, public-safe, and MVP-aligned."
