# CostPilot Policy: Default EC2 Instance Type
# 
# Purpose: Enforce cost-efficient instance type defaults
# Scope: Non-enterprise governance demonstration
# 
# This policy demonstrates CostPilot's basic policy enforcement
# capabilities without requiring enterprise features.

apiVersion: costpilot.io/v1
kind: Policy
metadata:
  name: default-ec2-type
  description: Enforce t3.micro as the default EC2 instance type for cost efficiency
  category: cost-optimization
  severity: medium

spec:
  resource_type: aws_instance
  
  rules:
    - name: enforce-instance-type
      description: Ensure new EC2 instances use cost-efficient t3.micro by default
      condition: |
        resource.instance_type != "t3.micro"
      
      action: flag
      
      message: |
        Instance type {{resource.instance_type}} detected.
        Default policy requires t3.micro for cost efficiency.
        Larger instances require explicit justification.
      
      recommendations:
        - Use t3.micro (2 vCPU, 1 GiB RAM) for development and testing
        - Use t3.small or larger only with documented justification
        - Consider burstable performance for variable workloads
      
      cost_impact:
        baseline: t3.micro ($0.0104/hour, ~$7.50/month)
        alternatives:
          - type: t3.small
            cost: "$0.0208/hour (~$15/month)"
            increase: "100%"
          - type: t3.medium
            cost: "$0.0416/hour (~$30/month)"
            increase: "300%"
          - type: t3.xlarge
            cost: "$0.1664/hour (~$120/month)"
            increase: "1500%"

  exceptions:
    - reason: production-workload
      requires_approval: true
    - reason: performance-testing
      requires_approval: true
    - reason: memory-intensive-application
      requires_approval: true

  enforcement:
    mode: advisory  # advisory, blocking, or audit-only
    applies_to:
      - main
      - feature/*
    
  metadata:
    owner: platform-team
    last_updated: "2025-12-06"
    demo_purpose: true
